export const PUNCHLINES = {
  emptyThrone: [
    "The realm has no leader, claim the throne for your own personal interest",
    "An empty throne is just an expensive chair. Fix that.",
    "No king, no rules. Actually, still no rules. But at least there'd be a king.",
    "The throne is cold. Warm it up with your ambition and questionable morals.",
    "Every great empire started with one degen saying 'I should be in charge.'",
    "The crown sits there, gathering dust. It deserves a head as empty as the throne.",
    "Leadership vacancy: no experience required, greed strongly preferred.",
    "Someone has to sit on that throne. Might as well be someone with your ego.",
    "The kingdom is in chaos. Perfect time to take over.",
    "That throne won't claim itself. Unless it's a smart throne. It's not.",
    "A kingdom without a king is just a bunch of people touching grass.",
    "The throne room echoes with silence. It should echo with your bad decisions instead.",
    "Imagine the power. Imagine the tokens. Imagine the maidens. Now stop imagining and bid.",
    "History remembers the bold. And sometimes the foolish. You could be both.",
    "No king means no taxes. Wait, there are always taxes. Might as well collect them.",
    "The royal treasury sits unguarded. That alone should motivate you.",
    "Last king got dethroned. Skill issue. You'd obviously do better.",
    "Fun fact: 100% of kings started by deciding they should be king.",
    "The realm needs a leader. A terrible one is still better than none. Probably.",
    "This throne has been empty for too long. The kingdom's WiFi password needs changing.",
    "Step up or shut up. The throne doesn't care about your feelings.",
    "Be the king your parents never wanted you to become.",
    "The crown awaits someone bold, reckless, and preferably liquid.",
    "A leaderless kingdom is like a wallet with no tokens. Fix it.",
    "They say heavy is the head that wears the crown. Your head looks strong enough.",
    "The throne is free real estate. For now.",
    "No king on the throne means nobody's getting rugged today. How boring.",
    "You miss 100% of the thrones you don't bid on. — Wayne Gretzky, probably.",
    "The kingdom has no direction. Neither do you. Perfect match.",
    "That chair has gold armrests. GOLD. What more do you need?",
    "Somebody's going to be king. Why let it be someone less degenerate than you?",
    "The throne is empty and the treasury is full. Connect the dots.",
    "A vacant throne is an insult to ambition everywhere.",
    "The people demand a ruler. They'll regret it, but they demand one.",
    "No king, no court jester. The kingdom is literally not fun right now.",
    "Claim the throne before your rival does. You know the one.",
    "An empty throne in a bull market? Criminal.",
    "The royal guards are just standing around. Give them someone to protect.",
    "Every moment without a king is a moment wasted. Time is tokens.",
    "Rise from the trenches and sit where you belong.",
    "Do it for the culture. Do it for the tokens. Do it because nobody can stop you.",
    "That throne has your name on it. Metaphorically. Literally would be weird.",
    "The realm cries out for leadership. Or at least for entertainment.",
    "You weren't born to be a peasant. At least that's what you tell yourself.",
    "Opportunity knocks. Actually, it's sitting on a golden throne staring at you.",
    "The only thing between you and the crown is a bid. And maybe common sense.",
    "Thrones don't stay empty forever. Neither does your wallet if you win.",
    "Be the main character. Bid for the crown.",
    "Fortune favors the bold. And the bold sit on thrones.",
    "The kingdom is a meme without a king. Be the meme lord.",
  ],

  candidateBidding: [
    "Think you can do better? Outbid this fool and take what's yours",
    "This pretender thinks they deserve the crown. Show them real ambition.",
    "Someone's about to be king and it's not you. Fix that.",
    "That candidate's wallet is sweating. Make it sweat harder.",
    "The current bid is cute. Yours should be cuter. And bigger.",
    "Are you really going to let this person rule over you?",
    "Every king was once a candidate nobody believed in. Don't believe in this one.",
    "The clock is ticking. Their smug face is waiting to be outbid.",
    "A pretender sits at the gates. Slam those gates shut with your tokens.",
    "They bid first but you can bid last. That's the one that matters.",
    "This candidate probably doesn't even have diamond hands. Outbid them.",
    "You're going to let THAT wallet be king? Seriously?",
    "The throne deserves better. You're better. Probably. Bid and find out.",
    "Their bid is temporary. Your reign could be eternal. Well, until someone attacks.",
    "Outbidding is not just a move, it's a lifestyle.",
    "Someone's getting comfortable. Make them uncomfortable with a bigger number.",
    "The candidate is already picking curtains for the throne room. Stop them.",
    "Imagine explaining to your grandkids that you could've been king but didn't bid.",
    "That wallet thinks it's about to be royalty. Humble it.",
    "The throne room has space for one. Make sure it's your wallet address on the door.",
    "Overbid or get ruled. Those are your only options.",
    "A wise man once said: 'always outbid the other guy.' Be that wise man.",
    "Their claim to the throne is as weak as their bid. Prove it.",
    "The candidate is one timer away from being king. Are you okay with that?",
    "Your tokens are meant for greatness. This bid is greatness calling.",
    "There's still time. The throne hasn't been handed over yet.",
    "This candidate's reign would be embarrassing. Save the kingdom.",
    "They want the crown? Make them pay more for it.",
    "The beauty of bidding: someone else's victory is never final until the timer hits zero.",
    "That candidate is already planning their royal feast. Crash it.",
    "Be the plot twist this bidding phase deserves.",
    "One bid stands between you and royalty. One bid.",
    "Their bid was bold. Yours should be bolder.",
    "The candidate thinks it's over. Show them it's just beginning.",
    "Why watch someone else become king when you have a perfectly good wallet?",
    "The crown doesn't care who bid first. It cares who bid last.",
    "Tick tock. Someone's about to be king. Don't let it be someone boring.",
    "The current candidate is one outbid away from being a footnote.",
    "You came here to spectate? Or to rule?",
    "Every token in that bid is a token you could've spent. Better spend yours.",
    "The pretender thinks they're safe. They don't know about you yet.",
    "In the game of thrones, you bid or you cope.",
    "That candidate has a head. The crown has a head-shaped hole. Don't let them meet.",
    "Someone's about to be very rich. Could be you. Could be them. Your call.",
    "This is the part where the hero outbids the villain. Be the hero. Or the villain. We don't judge.",
    "You've seen the bid. You've seen the wallet. You can do better in your sleep.",
    "The clock runs out and a king is born. Make sure it's the right one.",
    "They bid with confidence. Counter with arrogance.",
    "A challenger with deeper pockets always wins. Be that challenger.",
    "The throne is slipping away. Grab it while you still can.",
  ],

  idleKing: [
    "The king sits fat on his throne, pockets full of tokens and surrounded by maidens. Are you going to let him get away with it?",
    "Look at him up there, counting coins while you scroll Twitter. Disgusting.",
    "The king is living his best life with YOUR tokens. Probably.",
    "While you grind, the king vibes. This is the economy you chose.",
    "The king is so comfortable he started a podcast. Dethrone him.",
    "Imagine being this rich and this smug. Now imagine taking it all away.",
    "The royal treasury grows while the king does absolutely nothing. Relatable, actually.",
    "The king just bought another castle. With tokens from the peasants. As usual.",
    "He's literally rubbing coins together and laughing. You can hear it.",
    "The king hasn't done a single productive thing since coronation. Living the dream.",
    "Every second this king sits unchallenged, his ego grows. It's already critical.",
    "The king is hosting a banquet. You weren't invited. Start a war about it.",
    "Rumor has it the king is paperhanding his own treasury. Time to test that theory.",
    "The kingdom runs itself while the king takes credit. Some things never change.",
    "That crown is getting too comfortable on that head. Knock it off.",
    "The king wakes up, counts tokens, goes back to sleep. Peak monarchy.",
    "His royal highness is too busy touching grass to notice the approaching army. Good.",
    "The king thinks peace lasts forever. How adorable.",
    "Every empire falls. Some just need a little push. Or a lot of soldiers.",
    "The king is currently deciding between gold curtains and platinum curtains. End his dilemma.",
    "Peace in the kingdom means the king is profiting. War means everyone else gets a chance.",
    "The king posted 'feeling cute, might hold throne forever.' Prove him wrong.",
    "He's up there sipping from a golden goblet while you read this. Act accordingly.",
    "The longer the king sits, the richer he gets. The math isn't mathing for you.",
    "No active battle means the king sleeps soundly. Disturb his sleep.",
    "The king just referred to his subjects as 'exit liquidity.' Unacceptable.",
    "Royal life looks pretty good from down here. Take it from up there instead.",
    "The king is tweeting from the throne. Literally. Someone stop him.",
    "A peaceful kingdom is a boring kingdom. Spice things up.",
    "The treasury overflows while the peasants cope. Classic monarchy behavior.",
    "The king's approval rating is 0% among everyone who isn't the king.",
    "He didn't earn that crown, he outbid someone for it. You can outfight him for it.",
    "The king is so relaxed he started doing yoga in the throne room. This cannot stand.",
    "Imagine the memes if this king gets dethroned. Be the catalyst.",
    "The king thinks he's untouchable. Every king thinks that. Every king is wrong.",
    "His majesty is currently AFK. Perfect time to rally the troops.",
    "The king is stacking while you're reading punchlines. Priorities.",
    "That smug grin won't last forever. Nothing does. Especially in crypto.",
    "The king just minted an NFT of himself on the throne. He must be stopped.",
    "Pockets heavy, crown shiny, zero accountability. It's good to be king.",
    "The king's strategy is 'sit and collect.' Your strategy should be 'attack and disrupt.'",
    "Someone told the king he'd reign forever. Someone lied.",
    "The king is currently explaining to his court why he's definitely not a rug pull.",
    "All that gold, all that power, all from sitting in a chair. You could sit in that chair.",
    "The king is vibing so hard the throne is shaking. Help it shake more.",
    "He claimed the throne for personal interest. His personal interest is your tokens.",
    "The longer you wait, the fatter the king gets. Metaphorically. Maybe literally.",
    "A kingdom at peace is a kingdom waiting for chaos. Be the chaos.",
    "The king just whispered 'they'll never attack.' Famous last words.",
    "Every token in that treasury was someone else's dream. Time to wake up.",
  ],

  kingFighting: [
    "Look at him swinging that sword with bravery — when he's not hiding like a coward behind his treasury",
    "The king fights! Mostly because he has no choice. But still, he fights.",
    "Suddenly brave when the treasury is at stake. Funny how that works.",
    "The king drew his sword for the first time. He's holding it wrong.",
    "Turns out the king does know how to fight. Who knew? Not his army, apparently.",
    "Royal combat mode activated. Results may vary.",
    "The king fights like someone who learned swordplay from YouTube tutorials.",
    "From counting coins to swinging swords. Character development.",
    "The king's battle cry sounds suspiciously like 'not my tokens!'",
    "He polished that armor specifically for this moment. It's still shiny and untested.",
    "The king fights with the energy of someone protecting their leveraged position.",
    "Brave in battle, braver in treasury management. Priorities.",
    "The king is fighting so hard his crown almost fell off. Almost.",
    "War is hell. But losing the treasury is worse. Hence the sword.",
    "The king went from 'kingdom at peace' to 'panic mode' real quick.",
    "Every swing of that sword costs the kingdom's defense budget. Worth it? Debatable.",
    "The king discovered violence. The kingdom discovered entertainment.",
    "He fights not for honor, not for glory, but for the bag. Respect.",
    "The king's shield has a crown on it because of course it does.",
    "Battle-hardened? More like battle-anxious. But he's trying.",
    "The king fights like his portfolio depends on it. Because it does.",
    "From throne to frontline. The demotion nobody asked for.",
    "The king would rather fight an army than give up a single token. Understandable.",
    "His majesty is sweating. The crown is slipping. The battle rages on.",
    "The king fights with conviction. The conviction of a man who might lose everything.",
    "Sword in one hand, treasury key in the other. Balance.",
    "The king charged into battle. His financial advisor is having a heart attack.",
    "He trained for this moment. By which we mean he watched others fight from his balcony.",
    "The king's battle strategy: swing sword, hope for the best, protect tokens at all costs.",
    "The kingdom's fate rests on this man's sword arm. We should all be worried.",
    "Brave? Sure. Competent? The jury is still out.",
    "The king is fighting like a man possessed. Possessed by the fear of losing his loot.",
    "Who needs a standing army when you have a king with something to prove?",
    "The king entered the battlefield and immediately regretted leaving his accountant behind.",
    "Steel meets steel while the treasury watches nervously.",
    "The king fights with honor. And a backup plan. The backup plan is more soldiers.",
    "Turns out being king isn't all feasts and maidens. Sometimes it's swords and regret.",
    "The king's fighting stance says 'warrior.' His eyes say 'I want to go home.'",
    "Into battle he rides, fueled by adrenaline and the fear of becoming a peasant again.",
    "The king is giving it everything. 'Everything' might not be enough.",
    "He didn't sign up for actual combat. He signed up for the treasury. Life comes at you fast.",
    "The king fights like someone who just realized the crown comes with responsibilities.",
    "Sword raised, shield up, dignity questionable. The king battles on.",
    "The battlefield is where kings become legends. Or where they become ex-kings.",
    "The king's combat style: 70% desperation, 20% luck, 10% actual skill.",
    "He protects the kingdom. By which he means he protects his bank account.",
    "A king in battle is either inspiring or hilarious. This one is both.",
    "The crown stays on because of willpower. And maybe some tape.",
    "Fight, your majesty! Your throne, your tokens, and your reputation are at stake!",
    "The king didn't choose the battle life. The battle life outbid him for the choice.",
  ],

  attackPanel: [
    "Burn his kingdom down. No king deserves to sit comfortably.",
    "Send your soldiers. Let the king know peace was always temporary.",
    "Every soldier you send is a middle finger to royalty.",
    "Attack now. Ask questions never.",
    "The king's treasury won't burn itself. Well, actually it will. But help it along.",
    "Violence is not the answer. It's the question. The answer is yes.",
    "Your soldiers are ready. Your conscience is optional.",
    "The best defense is a good offense. The best offense is more soldiers.",
    "They built a kingdom. You brought a sledgehammer. Fair fight.",
    "Send troops like you send tweets. Aggressively and without thinking.",
    "Soldiers don't ask why. They ask how many.",
    "The king's walls are made of tokens. Your army is made of rage.",
    "Attack is just aggressive investment into regime change.",
    "Dethrone the king or die trying. Well, your tokens die trying. You're fine.",
    "An army marches on its stomach. Yours marches on pure spite.",
    "Release the troops. The king's comfort zone ends here.",
    "Some people talk about revolution. You fund one.",
    "Your soldiers carry swords. The king carries the weight of your incoming army.",
    "Every great downfall started with someone pressing the attack button.",
    "The pen is mightier than the sword. But swords are faster.",
    "You're not attacking a king. You're liberating a treasury.",
    "Send soldiers. Create chaos. Watch the crown wobble.",
    "Attack like your portfolio depends on it. It might.",
    "The king counted his gold today. He should've counted your soldiers instead.",
    "Your army doesn't need a reason. Just a direction. Point them at the throne.",
    "Chaos isn't a pit. Chaos is a ladder. Start climbing.",
    "Soldiers away! May they bring back glory, or at least good content.",
    "The throne looks fragile from this angle. Let's test that theory.",
    "Why let someone else be king when destruction is an option?",
    "Revolutions start small. One soldier at a time. Up to ten per click.",
    "Fire and fury. Mostly fury. Okay, entirely fury.",
    "The king's defense is only as strong as your attack is patient.",
    "Send in the troops. The treasury isn't going to redistribute itself.",
    "Think of it as aggressive decentralization.",
    "Your soldiers don't have 401ks. They have nothing to lose.",
    "The king's reign ends one soldier at a time.",
    "March forward. The throne is just a chair with better marketing.",
    "Attack: because diplomacy is for people who can't afford soldiers.",
    "Your army grows with every token. The king's anxiety grows faster.",
    "Siege the castle. Metaphorically. It's all on-chain. But siege it.",
    "The king made his bed. Your soldiers are about to unmake it.",
    "Tokens in, soldiers out, king down. Simple economics.",
    "Unleash your army like you unleash your opinions online. Without restraint.",
    "The king has guards. You have an army. Let them discuss.",
    "Every attack is a vote of no confidence. Send several.",
    "Storm the gates. Not literally. Blockchain gates. Send soldiers.",
    "The crown is heavy. Your army will help remove it.",
    "Attack first, strategize later. Or don't strategize at all. That works too.",
    "The sound of marching soldiers is the king's least favorite alarm clock.",
    "Your soldiers are sharpening their swords. The king should be sharpening his resume.",
  ],

  defendPanel: [
    "Simp for the king. Maybe he'll remember your loyalty. Probably not.",
    "Protect the crown. The king definitely won't share his treasury with you. But still.",
    "Your soldiers die for the king's bag. How noble of you.",
    "Defending the king is like holding someone else's bags. But with swords.",
    "The king needs you. He won't admit it, but he needs you.",
    "Stand between the king and his enemies. The king will be behind you. Way behind.",
    "Loyalty is its own reward. The actual reward goes to the king though.",
    "Defend the throne! The king promises to remember you. He won't.",
    "Your soldiers protect the king while the king protects his tokens. Teamwork.",
    "Noble defenders wanted. Pay: zero. Glory: also zero. But the king vibes.",
    "Shield wall! Because someone has to save the king from his own hubris.",
    "The king didn't ask for your help. He expects it. Different energy.",
    "Defend now, question your life choices later.",
    "Your loyalty is admirable. Your financial strategy is questionable.",
    "The king's treasury thanks you. The king himself? He's busy.",
    "Be the shield the king doesn't deserve but desperately needs.",
    "Defending royalty: the original unpaid internship.",
    "Your soldiers guard the throne while the king guards his DMs.",
    "The king sleeps soundly because of people like you. Think about that.",
    "Every defender makes the king stronger. And the king makes the king richer.",
    "Loyalty, honor, duty. Three things the king will not compensate you for.",
    "You defend, the king profits. Tale as old as time.",
    "Shield up! Your reward is the warm feeling of servitude.",
    "The king's survival strategy: let other people pay for his defense.",
    "Defend the crown because someone has to make poor financial decisions.",
    "Your soldiers fight for the king. The king fights for his bank account.",
    "Protecting the monarch: 0% APY but 100% good vibes.",
    "The defense of the realm is funded by suckers. Noble suckers, but suckers.",
    "Stand with the king! He's definitely standing behind you!",
    "Defend the throne. The king will write about your bravery in his journal. Maybe.",
    "Your shields protect the king. The king's shields protect his portfolio.",
    "Every soldier you send is proof that someone out there still believes in monarchy.",
    "Defend because chaos is bad. Or defend because you're already in too deep. Either works.",
    "The king recognizes your service. By 'recognizes' we mean he's vaguely aware of it.",
    "Hold the line! The king is counting on you! Also counting his tokens!",
    "Loyal subjects fight and the king reaps. Decentralization at its finest.",
    "The stronger the defense, the smugger the king. You're enabling him.",
    "Send defenders. The king's spa day depends on it.",
    "Your shields, your soldiers, the king's profit. Everyone plays their part.",
    "Defend the realm! Or at least defend the king's lifestyle.",
    "Sacrifice your tokens so the king doesn't have to sacrifice his. Classic.",
    "The king needs soldiers like crypto needs hopium. Desperately.",
    "Rally to the king's defense! He promises nothing in return! Transparency!",
    "Your defense makes the king invincible. Your wallet makes the king richer.",
    "Honor bound, token broke. The defender's oath.",
    "Stand firm, defenders! The king is watching! From a safe distance!",
    "Your loyalty will be remembered. In the king's memoir. In a footnote.",
    "Shield the king from harm. He can handle the treasury on his own, thanks.",
    "Defenders assemble! The king needs meat shields! Er, brave warriors!",
    "Protect the crown at all costs. All YOUR costs. The king keeps his.",
  ],
} as const;
